import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar, SidebarBody, SidebarLink } from "@/components/ui/Sidebar";
import {
  IconHome,
  IconUserBolt,
  IconSettings,
  IconLogout,
} from "@tabler/icons-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    { label: "Home", href: "/home", icon: <IconHome /> },
    { label: "Profile", href: "/profile", icon: <IconUserBolt /> },
    { label: "Settings", href: "/settings", icon: <IconSettings /> },
    { label: "Logout", href: "/logout", icon: <IconLogout /> },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row h-screen overflow-hidden">
          {/* Sidebar component */}
          <Sidebar>
            <SidebarBody>
              {links.map((link, index) => (
                <SidebarLink key={index} link={link} />
              ))}
            </SidebarBody>
          </Sidebar>
          {/* Main content */}
          <div className="flex-1 p-4 md:p-6 h-full overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
